version: 2
updates:
- package-ecosystem: "github-action"
    directory: "/"
    schedule:
      interval: "monthly"
- package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
